# Generated by Django 4.2.5 on 2023-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user_type',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
